---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: firstchart
  namespace: default
spec:
  releaseName: firstchart
  chart:
    git: git@github.com:garnaud/gitops-test
    ref: master
    path: ./
  values:
    replicas: 1
